[package]
name = "rust_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clokwerk = "0.4.0"
reqwest = { path ="../../opensource/reqwest", features = ["json","blocking"] }
tokio = { version = "1", features = ["full"] }
log = { version = "^0.4.17", features = ["std"] }
rocket = "0.5.0-rc.2"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.7"
slog-term = "2.9"
lazy_static = "1.4.0"
once_cell = "1.17.0"
slog-atomic = "3.1.0"
flume = "0.10.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
config = "0.13.3"
dotenv = "0.15.0"
concat-string = "1.0.1"
futures ="0.3"
tokio-test = "0.4.2"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "postgres","time", "chrono" ,"decimal"] }
schemars = "0.8.3"
rust_decimal = "1.28.0"
rust_decimal_macros = "1.28.0"
encoding = "0.2"
scraper = "0.14.0"
anyhow = "1.0"
