[package]
name = "rust_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
tokio-cron-scheduler = "0.9"
reqwest = { version = "0.11", features = ["json", "blocking", "brotli", "deflate", "gzip"] }
tokio = { version = "1", features = ["full"] }
log = { version = "^0.4.17", features = ["std"] }
#rocket = "0.5.0-rc.3"
lazy_static = "1.4"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
config = "0.13"
dotenv = "0.15"
concat-string = "1.0.1"
futures ="0.3"
tokio-test = "0.4.2"
rust_decimal = "1.30"
rust_decimal_macros = "1.30"
encoding = "0.2"
scraper = "0.16"
anyhow = "1.0"
crossbeam-channel = "0.5"
num_cpus = "1.15"
regex = "1"
ttl_cache = "0.5"
rayon = "1.7"
crossbeam = "0.8"
async-trait = "0.1"
redis = "0.23"
deadpool-redis = "0.12"
rand ="0.8"
urlencoding = "2.1"
tonic ={ version = "0.9", features = ["transport", "tls", "channel", "gzip"] }
prost = "0.11"
tokio-retry = "0.3"
hashbrown = "0.14"
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "time", "chrono", "bigdecimal", "macros", "rust_decimal"] }

[build-dependencies]
tonic-build = "0.9.2"
