name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Install PostgreSQL client
      run: sudo apt-get -yqq install postgresql-client

    - name: Run SQL file
      run: |
        export PGPASSWORD=password
        psql -h localhost -U user -d db -a -f etc/sql/market_category.sql
        psql -h localhost -U user -d db -a -f etc/sql/stocks.sql
        psql -h localhost -U user -d db -a -f etc/sql/daily_quote.sql
        psql -h localhost -U user -d db -a -f etc/sql/daily_money_history.sql
        psql -h localhost -U user -d db -a -f etc/sql/dividend.sql

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Verify protoc installation
      run: protoc --version

    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
